### ISSUE TITLE
Support exact match in search - media.list should show the action first in the side menu

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#34]
If there’s an exact match, simply present it on its own outside categories (e.g. “media.” Will show as usual but with open tree, and “media.list” will actually show the media.list action.)

**Comment by bobby-brennan** [comment]
Moving the full-match to the top of the menu looked kind of strange. Instead, I had it auto-navigate if there's a full match. LMK what you think.

**Comment by zoharbabin** [comment]
I am not sure it actually works... on too many occasions the redirect didn't work (the UI nor URL didn't change).
Also, not sure if it's a good UX, as when the user search they do expect to click the result to have the UI change, it's a bit awkward if the UI does things you're not expecting it to do.

**Comment by jessp01** [comment]
Just to make sure, are we talking about the API Console view or the API Docs? In the below, I am referring to API Console. In the docs search, I found several odd behaviours which I'll detail in a separate report.

I actually do see the main div change based on the search term but not in a predictable enough manner.

Inputting a full $SERVICE.$ACTION string [i.e "session.get" or "media.list"] does load the correct form/view. However, consider the search term "media" which currently loads "media.add" or "session" which loads "session.end". To me, that's undesirable and confusing. Personally, I think unless an exact match is found, the main div should remain empty and the user should select the desired
action from the nav menu.

**Comment by jessp01** [comment]
@bobby-brennan, @zoharbabin - any thoughts about my last comment?

**Comment by bobby-brennan** [comment]
Just changed this away from auto-navigation to instead show the exact match
at the top of the menu


Bobby Brennan
bobby.brennan@gmail.com

**Comment by jessp01** [comment]
Did you push? last commit I see in master is f3c8568af624babe35fd13f8cc6ab75781eada66

**Comment by bobby-brennan** [comment]
Whoops you're right, just pushed

On May 14, 2018 12:59 PM, "Jess Portnoy" <notifications@github.com> wrote:

Did you push? last commit I see in master is f3c8568
<https://github.com/kaltura/developer-platform/commit/f3c8568af624babe35fd13f8cc6ab75781eada66>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kaltura/developer-platform/issues/34#issuecomment-388889103>,
or mute the thread

**Comment by jessp01** [comment]
Hi @bobby-brennan,

It still behaves differently than what I think is ideal. IMHO:
- When first loading /console, the main div [`_ngcontent-c2`] should be empty, or perhaps display an introductory paragraph ending with "Select an action to load" or something along these lines. Right now service/accessControl/action/add is loaded, simply because it happens to be first service.action pair when going by alphabetical order
- If the search term matches a service.action pair exactly [say `media.list` or `session.start`] then the corresponding form should be loaded in the div.

@zoharbabin - thoughts?

**Comment by bobby-brennan** [comment]
I think we decided against auto-navigating if there's an exact match.
Instead we show the exact match at the top.

I'm all for having an intro page for the API console - just need to know
what to put there.

Bobby Brennan
bobby.brennan@gmail.com

**Comment by zoharbabin** [comment]
as for auto-navigate, if you all agree - ok.
as for intro for the API, we already have such an overview page, no?

**Comment by jessp01** [comment]
We have https://developer.kaltura.com:8443/api-docs/Overview which I also understand Avital should provide a revised version for.. or do you mean something else?

I think we should have a dedicated and short intro paragraph for the API console specifically. Short being the operative word here:) I just don't feel it makes sense for

**Comment by zoharbabin** [comment]
Agree. @tzubeli - Can you please propose an intro text for the console?

**Comment by jessp01** [comment]
@tzubeli - when you're ready, also push the modified overview version here:
https://github.com/kaltura/developer-platform-docs/blob/master/documentation/overview.md

So we can review it, generate the HTML file and update the site.

@bobby-brennan - let's enable the auto navigation upon exact match behaviour as per https://github.com/kaltura/developer-platform/issues/34#issuecomment-389849860

**Comment by jessp01** [comment]
@bobby-brennan - reminder:)
@zoharbabin, @tzubeli - any updates on this?

**Comment by bobby-brennan** [comment]
Yup, all changes are in the LucyBot code.

I'm working through the remaining TODOs today and tomorrow

**Comment by jessp01** [comment]
Exact match now works beautifully:) All that's missing is the intro page. Once in place, we can mark this as done.

**Comment by jessp01** [comment]
All done.
