### ISSUE TITLE
Switching between accounts of the same logged in user

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#45]
Add ability to switch accounts (currently it requires logoff and login again). Important capability for customers who manage multiple accounts (e.g. staging and production, or parent and sub accounts).

**Comment by bobby-brennan** [comment]
This should be the same as the partnerId dropdown that happens in step 2 of the login, right?

**Comment by jessp01** [comment]
Hi @bobby-brennan,

That's correct. What client.partner.listPartnersForUser() returns; same as here:
https://github.com/kaltura/developer-platform/blob/master/routes/partner-auth.js#L45

**Comment by jessp01** [comment]
Hi @bobby-brennan -
I agree that it would be insecure to store the kuser's passwd or the adminSecret for each partner, which partner.listPartnersForUser() returns, for that matter, in a cookie/localStorage.
However, there is an action called `user.loginByKs()` which can accept a KS and a `requestedPartnerId` param. Provided the KS passed to this action belongs to a kuser that is associated with the `requestedPartnerId`, this will return a new KS where the partner ID matches partnerId.

Since the LucyBot app has such a KS stored, it should work.

**Comment by bobby-brennan** [comment]
The latest kaltura client for node (3.3.3) doesn't seem to have `user.loginByKs`...

**Comment by jessp01** [comment]
Hi @bobby-brennan,

The `kaltura` npm is the old client. You will need to use the `kaltura-client` NPM which does implement this action.
https://nodei.co/npm/kaltura-client/

Or, you can use the archive directly http://cdnbakmi.kaltura.com/content/clientlibs/node_26-04-2018.tar.gz

See also https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS/blob/master/KalturaServices.js#L5855

Thanks,

**Comment by bobby-brennan** [comment]
Thanks! Now using `loginByKs`: 9981db9c1743716f03d7e0b3c0331a3f97de13ec

**Comment by jessp01** [comment]
Works well:)
