### ISSUE TITLE
Add code generation support for Kaltura's Swift SDK

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#46]
@tan-tan-kanarek - please add information regarding this new client, docs, examples, important notes for how to create the code gen for it.

**Comment by tan-tan-kanarek** [comment]
Simple test: https://github.com/kaltura/KalturaGeneratedAPIClientsSwift/blob/master/Example/Tests/MediaServiceTest.swift

Plugin test: https://github.com/kaltura/KalturaGeneratedAPIClientsSwift/blob/master/Example/Tests/PluginsTest.swift

**Comment by bobby-brennan** [comment]
@tan-tan-kanarek @jessp01 I have a first pass at Swift codegen, but haven't been able to get it to run on Ubuntu 16.04. I have `swift` installed, but no matter what I do I get this message:

```
error: no such module 'KalturaClient'
```

Since I'm not on OSX, I don't have access to xcode, so the setup instructions in the client lib repo don't work for me. Any tips?

**Comment by bobby-brennan** [comment]
Here's the generated code: https://github.com/kaltura/developer-platform/blob/master/test/golden/with_setup/swift.swift

**Comment by jessp01** [comment]
@tan-tan-kanarek - since the Swift client requires frameworks that are not available on Linux, such as UIKit [see https://exceptionshub.com/swift-package-manager-uikit-dependency.html] and MobileCoreServices, neither Bobby nor I can properly validate the generated code.
Can you please go through examples generated here: https://developer.kaltura.com:8443 when choosing "swift" and confirm that they work?

Thanks,

**Comment by tan-tan-kanarek** [comment]
I'll check it and will let you know.

**Comment by zoharbabin** [comment]
@tan-tan-kanarek - Any update on this? We want to go live with the new site soon... Thanks!

**Comment by tan-tan-kanarek** [comment]
See https://github.com/kaltura/developer-platform/pull/64

**Comment by jessp01** [comment]
See my comment here: https://github.com/kaltura/developer-platform/pull/64#issuecomment-392581665

**Comment by jessp01** [comment]
@bobby-brennan - any thoughts about https://github.com/kaltura/developer-platform/issues/46#issuecomment-392582454?

**Comment by bobby-brennan** [comment]
Yup should be an easy fix.

**Comment by bobby-brennan** [comment]
Fixed in cd16dd5687e1a7cb6d2cf1559ff49a472bb163ca

**Comment by jessp01** [comment]
Looking good.
