### ISSUE TITLE
Add codegen for the new Angular Client Library

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#50]
Generated Client: https://github.com/kaltura/KalturaGeneratedAPIClientsAngular/
Client Generator: https://github.com/kaltura/clients-generator/tree/master/lib/ngx 

See tests here -
https://github.com/kaltura/KalturaGeneratedAPIClientsAngular/blob/master/src/api/tests 

@bobby-brennan - please let me know estimated time for this task, and whether you have questions.

**Comment by bobby-brennan** [comment]
Cool! Looks like this is a full TypeScript client rather than something angular-specific. Do you want to list it as Angular or TypeScript?

Should take an additional 6 hours.

**Comment by jessp01** [comment]
@bobby-brennan - certain parts of this client do rely on Angular specific libraries.
For instance:
https://github.com/kaltura/KalturaGeneratedAPIClientsAngular/blob/master/src/kaltura-client.service.ts#L1

Guess we should label this client as "AngularJS". 
There is [yet] another, pure TS client here:
https://github.com/kaltura/KalturaGeneratedAPIClientsTypescript/
but we're not going to create a codegen implementation for it at present time,

**Comment by kaltura-hooks** [comment]
Hi @zoharbabin,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by zoharbabin** [comment]
I am wondering if we should code-gen this client at all, or wait for the native TypeScript client to code-gen?

**Comment by jessp01** [comment]
I suppose the real question here is why @esakal created the Angular client to begin with. 
Once we answer that, we'll be able to make a more informed decision. 
As far as I know, it's currently used in [KMCng](https://github.com/kaltura/KMCng) exclusively but it's possible other teams/projects make use of it as well. 
The TS client, also created by @esakal and team, actually preceded the Angular one and at a certain point, I know the KMCng team pondered deprecating it only it turned out another Kaltura team uses it.

**Comment by bobby-brennan** [comment]
@jessp01 @esakal I'm having trouble with the Angular client. The code compiles successfully, but it never sends the request to `session.start` - it just hangs. Here's my code:

https://github.com/kaltura/developer-platform/blob/master/test/golden/with_setup/angular.ts

Any ideas?

**Comment by jessp01** [comment]
Hey @bobby-brennan,

Can you please compare yours against the test here:
https://github.com/kaltura/KalturaGeneratedAPIClientsAngular/blob/a7087c411a4c666ed2afb0ea52c1352326927a2c/src/tests/utils.ts#L32
?

I see a few differences..

@esakal - can you please explain
```
partnerId: <any>TestsConfig.partnerId * 1
```
?

**Comment by bobby-brennan** [comment]
Yup, that's what I'm using as my template.

**Comment by jessp01** [comment]
@bobby-brennan - can you please post the outgoing request as captured by a HTTP sniffer? Can save some time:)

**Comment by bobby-brennan** [comment]
There is no outgoing request, the code just hangs

**Comment by jessp01** [comment]
I see... @esakal - please take a look?

**Comment by esakal** [comment]
@zoharbabin 

> I am wondering if we should code-gen this client at all, or wait for the native TypeScript client to code-gen?

I'm not sure I understand so I will provide a quick explanation on what we currently have. We currently have two types of clients, both rely on Typescript: 

- Pure typescript client 
- Angular/Typescript client

Both clients are relevant and choosing between them is a matter of the application technology stack.  Applications that using typescript will choose the `Pure typescript client` (i.e applications that are using React with Typescript), while Angular based application will favor the `Angular typescript client` which is native to that framework.

Both of them are fully operational so I think you can/should add both of them. @jessp01 is right, we planed to deprecate the typescript library in the end we decided to continue and maintain it.

**Comment by esakal** [comment]
Hi @bobby-brennan,
Please see #57 
Yours,
Eran.

**Comment by zoharbabin** [comment]
@bobby-brennan and @jessp01 - Considering Eran's above comment, can we also add the TypeScript client? 

I've seen demand recently for React client.. and while we won't really be investing in React soon, TypeScript should provide a good enough basis for React users.

**Comment by jessp01** [comment]
That's fine by me.
@bobby-brennan - units for this client can be found here:
https://github.com/kaltura/KalturaGeneratedAPIClientsTypescript/tree/master/src/tests

@esakal - while this is not blocking the work on the code generator, note that some of the units currently fail, see:
https://travis-ci.org/kaltura/KalturaGeneratedAPIClientsTypescript/jobs/379209094#L1507

I recall pointing that out before and verifying it was fixed... can you take a look?

**Comment by zoharbabin** [comment]
I've opened: 
#61

**Comment by bobby-brennan** [comment]
I think this issue can be closed.

**Comment by jessp01** [comment]
Hi @bobby-brennan - I assume you've run some basic tests with the generated code? I don't really work with Angular JS much [I know you do, obviously] so if you already tested, there's no need for me to fiddle with it and you can just close it.

**Comment by bobby-brennan** [comment]
Yup, I copied them into an existing angular project to test. Will close

On Jun 6, 2018 4:33 PM, "Jess Portnoy" <notifications@github.com> wrote:

Hi @bobby-brennan <https://github.com/bobby-brennan> - I assume you've run
some basic tests with the generated code? I don't really work with Angular
JS much [I know you do, obviously] so if you already tested, there's no
need for me to fiddle with it and you can just close it.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kaltura/developer-platform/issues/50#issuecomment-395204334>,
or mute the thread
