### ISSUE TITLE
Console issues with data entry and fileAsset

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#71]
Please see attached screenshots.

1. data.update action is using documentEntry instead of dataEntry.
<img width="1435" alt="data-update-wrong-entry-type" src="https://user-images.githubusercontent.com/150514/42737466-924d43d4-887c-11e8-8dd6-d474495d5624.png">

2. data.get entryId field is showing a dropdown of MEDIA entries instead of data entries... in non-Media entries it's best to keep this field an open text.
<img width="1439" alt="dropdown-data-get" src="https://user-images.githubusercontent.com/150514/42737467-926d3b26-887c-11e8-8130-38b6c728dbbf.png">

3. fileAsset.get id field is showing a dropdown instead of int filed, and it's also broken.
<img width="1429" alt="fileasset-get-id" src="https://user-images.githubusercontent.com/150514/42737465-920f7ed2-887c-11e8-8d5d-e161fc94d64b.png">

**Comment by bobby-brennan** [comment]
For 1. the schema says the name should be `documentEntry`, but it is still using `KalturaDataEntry` as the object:

```xml
<action name="update" description="Update data entry. Only the properties that were set will be updated." enableInMultiRequest="1" sessionRequired="always">
<param name="entryId" type="string" optional="0" description="Data entry id to update"/>
<param name="documentEntry" type="KalturaDataEntry" optional="0" description="Data entry metadata to update"/>
<result type="KalturaDataEntry"/>
<throws name="ENTRY_ID_NOT_FOUND"/>
</action>
```

```json
{
              "properties": {
                "documentEntry": {
                  "$ref": "#/definitions/KalturaDataEntry"
                },
                "entryId": {
                  "type": "string"
                }
              },
}
```

For 2 and 3, I removed the dynamic dropdowns for everything but `entryId` in `media` operations just to be safe. Should be good at latest.

**Comment by jessp01** [comment]
RE ##2, ##3 - will check an deploy to Prod. later.

RE ##1 - the code in question is here:
https://github.com/kaltura/server/blob/Naos-14.3.0/api_v3/services/DataService.php#L88

Notice however that the TYPE is correct, it's only the name that's confusing:
```php
// * @param KalturaDataEntry $documentEntry Data entry metadata to update
function updateAction($entryId, KalturaDataEntry $documentEntry)
```

**Comment by jessp01** [comment]
fixes for #2 and #3 deployed to Prod.
Can be tested at https://developer.kaltura.com.

**Comment by jessp01** [comment]
@zoharbabin - can we close this?

**Comment by jessp01** [comment]
@zoharbabin - ping?:)

**Comment by kaltura-hooks** [comment]
Hi @zoharbabin,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,
