### ISSUE TITLE
Youtube videos added in mediaspace not reflecting in KMC console.

### ISSUE THREAD

**Issue by saivaradula** [kaltura/developer-platform#9]
Hello:
I am working on a web app where KMC videos software is used. I am all new to this technology.
I am able to get the list of videos from KMC to website. 
However, I tried adding the videos from youtube using mediaspace admin access.
I have added new channel and the new channel is reflected in KMC console. but, I am not able to view the list of videos added in mediaspace admin in KMC console.

I am not sure where I am doing wrong. 
A suggestion would be a great help.

- Sai

**Comment by kaltura-hooks** [comment]
Hi @saivaradula,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hello @saivaradula,

Since you've mentioned MediaSpace, I gather you are a Kaltura SasS customer.
This repo really has nothing to do with your issue or with MediaSpace, it is used to generate developer.kaltura.com.
To address your issue, please open a ticket with our support team. 
Thanks,

**Comment by saivaradula** [comment]
Thank you. I have added in community.

**Comment by saivaradula** [comment]
I am sorry to bother on this.
I could not find the support page url. Can you please suggest me. 

- Sai
